appuio/terraform-openshift4-cloudscale

- .gitignore
- README.md
- backend.tf
- main.tf
- output.tf
- provider.tf
- templates/haproxy.cfg
- templates/ignition.tmpl
- templates/keepalived.conf
- variables.tf
Together with https://github.com/appuio/openshift4-docs/pull/21
> Initial setup

- templates/haproxy.cfg
Allow missing DNS records on startup.
> Fix HAProxy DNS issue

- lb.tf
- master.tf
- modules/node-group/variables.tf
- variables.tf
According to the documentation [1].
[1] https://kb.vshn.ch/products/vss_ocp4_cloudscale.html#_default_configuration_minimum_requirements
> Update default falvors

- modules/node-group/versions.tf
- provider.tf
- versions.tf
Required for https://github.com/appuio/component-openshift4-cloudscale/pull/4
Relates to https://ticket.vshn.net/browse/APPU-2879
> Upgrade to Terraform v0.13

- bootstrap.tf
- modules/node-group/main.tf
- outputs.tf
- variables.tf
- versions.tf
> Support for OCP 4.7

- lb.tf
- outputs.tf
> Fix hieradata_mr_url error when lb_count is 0

- lb.tf
- variables.tf
> Allow passing team for LBaaS

- lb.tf
- variables.tf
See appuio/terraform-openshift4-cloudscale#37
> Allow attaching LBs to additional networks

- lb.tf
- variables.tf
> Add support for enabling proxy protocol on the load-balancers

- lb.tf
> Update terraform-modules to `v2.4.0`, introducing PTR records for LBs

- provider.tf
Use 4.0 provider, pin to < 5 to prevent breaking changes like with 4.0
https://github.com/cloudscale-ch/terraform-provider-cloudscale/blob/master/CHANGELOG.md#400
> Pin cloudscale terraform provider to 4.0

- templates/dns.zone
> Fix apps domain record

- lb.tf
- master.tf
- modules/node-group/variables.tf
- variables.tf
> Switch to new cloudscale.ch flavors

- lb.tf
- master.tf
- variables.tf
Make the flavor for the master nodes and loadbalancers configurable, e.g. for using a flex flavor.
> Make master and loadbalancer compute flavors configurable

- variables.tf
https://ticket.vshn.net/browse/OCP-626
> Set default infra node count to `4` to adjust for new default logging.

- lb.tf
- outputs.tf
- variables.tf
> Add optional support for using existing floating IPs

- lb.tf
> Use worker nodes as router backends if no infra nodes are provisioned

- lb.tf
- outputs.tf
See also https://github.com/appuio/terraform-modules/pull/54
> Revert indexing changes from #81

- lb.tf
- main.tf
- outputs.tf
- templates/dns.zone
- variables.tf
> Add support to customize the internal API VIP and add a variable to configure an internal router VIP

- modules/node-group/main.tf
Follow up of https://github.com/appuio/machine-api-provider-cloudscale/pull/13
> Include cluster ID as server tag

- .github/workflows/auto-release.yaml
- .github/workflows/release.yaml
> Setup auto-release workflow
